version: '2'

networks:
  nextcloud-network:
    driver: bridge

services:

  postgres:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    networks:
      - nextcloud-network
    expose:
      - "5432"
    volumes:
      - ${PATH_PGDATA}:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS="--data-checksums"

  nextcloud:
    image: nextcloud:12.0.4
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT_NEXTCLOUD_HTTP}:80"
      - "${PORT_NEXTCLOUD_HTTPS}:443"
    depends_on:
      - postgres
    volumes:
      - ${PATH_NEXTCLOUD}:/var/www/html
    networks:
      - nextcloud-network
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres
